[package]
name = "torr"
version = "0.1.0"
edition = "2024"

[dependencies]
sha1 = "0.10"
hex = "0.4"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
rand = "0.8"
thiserror = "1"
percent-encoding = "2.3.1"
